version: "3"
services:
  app:
    container_name: socialcops
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - socialmongo
  socialmongo:
    container_name: socialmongo
    image: mongo
    ports:
      - "27017:27017"
